name: Deploy to GCP and GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'pom.xml'
      - 'front/stocks-stats/**'
      - '.github/**'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE_NAME: stocks-stats
  REGION: us-central1

jobs:
  backend-deploy:
    name: Backend - Build and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Get version from pom.xml
        run: echo "APP_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build --build-arg JAR_FILE=target/stocks-stats-${{ env.APP_VERSION }}.jar -t gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ env.APP_VERSION }}-$GITHUB_SHA .
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ env.APP_VERSION }}-$GITHUB_SHA

      - uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: stock-stats-cluster
          location: ${{ env.REGION }}

      - name: Deploy to GKE
        run: |
            if ! kubectl get secret stocks-stats-secrets &> /dev/null; then
            kubectl create secret generic stocks-stats-secrets \
            --from-literal=DATABASE_URL='***' \
            --from-literal=DATABASE_USERNAME='***' \
            --from-literal=DATABASE_PASSWORD='***' \
            --from-literal=N_THREADS='***' \
            --from-literal=REDDIT_API_KEY='***' \
            --from-literal=REDDIT_SECRET_KEY='***'
            fi
            
            kubectl apply -f .github/kubernetes/gke-deploy.yml
            
            kubectl rollout status deployment/stocks-stats --timeout=300s

  frontend-deploy:
    name: Frontend - Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install and Build Frontend
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        run: |
          cd front/stocks-stats
          npm ci
          npm run build

      - name: Deploy Frontend to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./front/stocks-stats/out
          cname: stocks.adrianlopez.tech