name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: my-cluster
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: stocks-stats

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Get version from pom.xml
        run: |
          APP_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: 'gke-gcloud-auth-plugin'

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Get GKE Credentials
        run: gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }}

      - name: Build and Push Docker image
        run: |
          docker build --build-arg JAR_FILE=target/stocks-stats-${{ env.APP_VERSION }}.jar -t gcr.io/$PROJECT_ID/$DEPLOYMENT_NAME:${{ env.APP_VERSION }}-$GITHUB_SHA .
          docker push gcr.io/$PROJECT_ID/$DEPLOYMENT_NAME:${{ env.APP_VERSION }}-$GITHUB_SHA

      - name: Update deployment file
        run: |
          sed -i "s|APP_VERSION|${{ env.APP_VERSION }}|g; s|GITHUB_SHA|${{ github.sha }}|g" .github/kubernetes/deployment.yaml

      - name: Deploy to GKE
        run: kubectl apply -f .github/kubernetes/deployment.yaml