name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: my-cluster
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: stocks-stats

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Get version from pom.xml
        run: |
          APP_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          install_components: 'gke-gcloud-auth-plugin'

      - name: Install GKE Auth Plugin
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Configure Docker
        run: |
          gcloud --quiet auth configure-docker

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }}

      - name: Build Docker image
        run: |
          docker build --build-arg JAR_FILE=target/stocks-stats-${{ env.APP_VERSION }}.jar -t gcr.io/$PROJECT_ID/$DEPLOYMENT_NAME:${{ env.APP_VERSION }}-$GITHUB_SHA .

      - name: Push Docker image
        run: |
          docker push gcr.io/$PROJECT_ID/$DEPLOYMENT_NAME:${{ env.APP_VERSION }}-$GITHUB_SHA

      - name: Update deployment file
        run: |
          sed -i "s|APP_VERSION|${{ env.APP_VERSION }}|g; s|GITHUB_SHA|${{ github.sha }}|g" .github/kubernetes/deployment.yaml

      - name: Deploy to GKE
        env:
          USE_GKE_GCLOUD_AUTH_PLUGIN: True
        run: |
          kubectl apply -f .github/kubernetes/deployment.yaml